# Generated by Django 4.2.7 on 2025-10-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("theory", "0002_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="theorycategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="theory.theorycategory",
                verbose_name="Catégorie parent",
            ),
        ),
    ]
