# Generated by Django 4.2.7 on 2025-10-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theory", "0003_theorycategory_parent"),
    ]

    operations = []
