# Generated by Django 4.2.7 on 2025-08-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="instagram",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Compte Instagram"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="website",
            field=models.URLField(blank=True, verbose_name="Site web"),
        ),
    ]
