# Generated by Django 4.2.7 on 2025-08-13 15:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("competitions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="competition",
            name="competition_categor_88250d_idx",
        ),
        migrations.RenameField(
            model_name="competition",
            old_name="promotional_video",
            new_name="video_url",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="difficulty",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="is_free",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="jury_members",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="min_participants",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="organizers",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="prizes",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="rehearsal_date",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="time_limit",
        ),
        migrations.AddField(
            model_name="competition",
            name="age_groups",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Groupes d'âge"
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="judges",
            field=models.ManyToManyField(
                blank=True,
                related_name="competition_judging",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Juges",
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="prize_distribution",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Distribution des prix"
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="time_limits",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Limites de temps"
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="category",
            field=models.CharField(
                choices=[
                    ("solo", "Solo"),
                    ("couple", "Couple"),
                    ("group", "Groupe"),
                    ("professional", "Professionnel"),
                    ("amateur", "Amateur"),
                    ("youth", "Jeunesse"),
                    ("senior", "Senior"),
                ],
                default="couple",
                max_length=20,
                verbose_name="Catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="judging_criteria",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Critères de jugement"
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="max_participants",
            field=models.PositiveIntegerField(
                default=50,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name="Nombre maximum de participants",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="registration_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=8,
                verbose_name="Frais d'inscription",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="rules",
            field=models.TextField(blank=True, verbose_name="Règlement"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("registration_open", "Inscriptions ouvertes"),
                    ("registration_closed", "Inscriptions fermées"),
                    ("ongoing", "En cours"),
                    ("completed", "Terminée"),
                    ("cancelled", "Annulée"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AddIndex(
            model_name="competition",
            index=models.Index(
                fields=["category", "status"], name="competition_categor_b5b81a_idx"
            ),
        ),
    ]
