# Generated by Django 4.2.7 on 2025-08-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "competitions",
            "0002_remove_competition_competition_categor_88250d_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="instagram",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Compte Instagram"
            ),
        ),
    ]
